# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivationcode',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserActivationCode',
        ),
    ]
